#!/usr/bin/env bun
/**
 * Pre-commit guard: rejects staged files exceeding 1MB (1048576 bytes).
 * Generated by @mdrv/lhg
 */
import { statSync } from 'node:fs'

const MAX_BYTES = 1048576
const MAX_LABEL = '1MB'
const args = process.argv.slice(2)

if (args.length === 0) process.exit(0)

const violations: string[] = []

for (const file of args) {
	try {
		const stat = statSync(file)
		if (stat.size > MAX_BYTES) {
			violations.push(`  ${file} (${formatSize(stat.size)})`)
		}
	} catch {}
}

if (violations.length > 0) {
	console.error(`❌ Files exceed max size (${MAX_LABEL}):\n${violations.join('\n')}`)
	process.exit(1)
}

function formatSize(bytes: number): string {
	if (bytes >= 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)}MB`
	if (bytes >= 1024) return `${(bytes / 1024).toFixed(1)}KB`
	return `${bytes}B`
}
